# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(121212)
$foreground = rgb(D6D6D6)
$color0 = rgb(3A3A3A)
$color1 = rgb(0D0D0E)
$color2 = rgb(131314)
$color3 = rgb(3C3C3C)
$color4 = rgb(404041)
$color5 = rgb(676868)
$color6 = rgb(676868)
$color7 = rgb(BCBDBD)
$color8 = rgb(838484)
$color9 = rgb(121213)
$color10 = rgb(19191A)
$color11 = rgb(505050)
$color12 = rgb(555656)
$color13 = rgb(898B8B)
$color14 = rgb(898B8B)
$color15 = rgb(BCBDBD)
