# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000000)
$foreground = rgb(F5F5F2)
$color0 = rgb(000000)
$color1 = rgb(666861)
$color2 = rgb(797A73)
$color3 = rgb(9A9D95)
$color4 = rgb(9EA098)
$color5 = rgb(A9A8A2)
$color6 = rgb(AAAAA4)
$color7 = rgb(E8E8E5)
$color8 = rgb(A3A2A0)
$color9 = rgb(888A82)
$color10 = rgb(A2A39A)
$color11 = rgb(CDD1C6)
$color12 = rgb(D3D6CB)
$color13 = rgb(E1E0D8)
$color14 = rgb(E2E2DB)
$color15 = rgb(E8E8E5)
