# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000000)
$foreground = rgb(EEEFEF)
$color0 = rgb(000000)
$color1 = rgb(2B2B2C)
$color2 = rgb(323233)
$color3 = rgb(5C5D5D)
$color4 = rgb(616262)
$color5 = rgb(8D8E8E)
$color6 = rgb(9B9C9C)
$color7 = rgb(DEDFDF)
$color8 = rgb(9B9C9C)
$color9 = rgb(393A3A)
$color10 = rgb(434344)
$color11 = rgb(7A7C7C)
$color12 = rgb(818283)
$color13 = rgb(BBBDBD)
$color14 = rgb(CED0D0)
$color15 = rgb(DEDFDF)
