# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E2E2E1
background         #445037
cursor             #84847E

active_tab_foreground     #445037
active_tab_background     #E2E2E1
inactive_tab_foreground   #E2E2E1
inactive_tab_background   #445037

active_border_color   #E2E2E1
inactive_border_color #445037
bell_border_color     #AAAAA4

color0      #EEEFEE
color1		#AAAAA4
color2		#A9A8A2
color3		#9EA098
color4		#9A9D95
color5		#797A73
color6		#666861
color7		#666663
color8		#9F9E99
color9		#E2E2DB
color10		#E1E0D8
color11		#D3D6CB
color12		#CDD1C6
color13		#A2A39A
color14		#888A82
color15		#E8E8E5
