# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D5D3D2
background         #1C2833
cursor             #6A7D7C

active_tab_foreground     #1C2833
active_tab_background     #D5D3D2
inactive_tab_foreground   #D5D3D2
inactive_tab_background   #1C2833

active_border_color   #D5D3D2
inactive_border_color #1C2833
bell_border_color     #ACA9A4

color0      #A3A19F
color1		#ACA9A4
color2		#9AA4A1
color3		#9C9D9A
color4		#747267
color5		#526F71
color6		#5F6262
color7		#676662
color8		#A19E99
color9		#E6E2DA
color10		#CEDBD6
color11		#D0D2CD
color12		#9B9889
color13		#6E9496
color14		#7F8383
color15		#EAE8E4
