# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FDF3D5
background         #141112
cursor             #BD9888

active_tab_foreground     #141112
active_tab_background     #FDF3D5
inactive_tab_foreground   #FDF3D5
inactive_tab_background   #141112

active_border_color   #FDF3D5
inactive_border_color #141112
bell_border_color     #542B22

color0      #3C393A
color1		#542B22
color2		#5D2E2C
color3		#8A4734
color4		#A6553D
color5		#806670
color6		#BCA665
color7		#F4E6BB
color8		#ABA183
color9		#6F3A2E
color10		#7C3D3B
color11		#B95F45
color12		#DD7151
color13		#AB8895
color14		#FADE87
color15		#F4E6BB
